[package]
name = "cybersentinel-alerting"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "CyberSentinel alerting stage"

[lints]
workspace = true

[dependencies]
cybersentinel-common.workspace = true
